import { Component, OnInit } from "@angular/core";

const data = [
	{
		_id: 1,
		composer: "Tom Jobim",
		key: "Bb",
		name: "Samba De Uma Nota",
		style: "Bossa Nova",
		tempo: 112,
	},
	{
		_id: 2,
		composer: "Chick Corea",
		key: "Em",
		name: "500 Miles High",
		style: "Latin Jazz",
		tempo: 130,
	},
	{
		_id: 3,
		composer: "Caetano Veloso",
		key: "Dm",
		name: "Qualquer Coisa",
		style: "Mpb",
		tempo: 92,
	},
	{
		_id: 4,
		composer: "Compay Segundo",
		key: "Dm",
		name: "Lagrimas Negras",
		style: "Son Cubano",
		tempo: 106,
	},
	{
		_id: 5,
		composer: "Zé Keti",
		key: "D",
		name: "Diz Que Fui Por Aí",
		style: "Samba",
		tempo: 96,
	},
	{
		_id: 6,
		composer: "John Coltrane",
		key: "Eb",
		name: "Giant Steps",
		style: "Jazz Bebop",
		tempo: 220,
	},
	{
		_id: 7,
		composer: "Tom Jobim",
		key: "Bb",
		name: "Triste",
		style: "Bossa Nova",
		tempo: 106,
	},
	{
		_id: 8,
		composer: "Edu Lobo",
		key: "Dm",
		name: "Casa Forte",
		style: "Baião Jazz",
		tempo: 136,
	},
	{
		_id: 9,
		composer: "Hermeto Pascoal",
		key: "Dm",
		name: "Forró Brasil",
		style: "Baião Jazz",
		tempo: 120,
	},
	{
		_id: 10,
		composer: "Kiko Horta",
		key: "Am",
		name: "Forró Transcendental",
		style: "Baião Jazz",
		tempo: 100,
	},
	{
		_id: 11,
		composer: "Sivuca",
		key: "G",
		name: "Um Tom Pra Jobim",
		style: "Forró Choro",
		tempo: 110,
	},
	{
		_id: 12,
		composer: "Hamilton De Holanda",
		key: "Gm",
		name: "Xote Do Almeidinha",
		style: "Xote",
		tempo: 78,
	},
	{
		_id: 13,
		composer: "Sivuca",
		key: "Am",
		name: "Feira De Mangaio",
		style: "Baião ",
		tempo: 110,
	},
	{
		_id: 14,
		composer: "Hermeto Pascoal",
		key: "G",
		name: "Forró Pela Manhã",
		style: "Baião Jazz",
		tempo: 100,
	},
	{
		_id: 15,
		composer: "Edu Lobo",
		key: "Em",
		name: "Ponteio ",
		style: "Baião Jazz",
		tempo: 120,
	},
	{
		_id: 16,
		composer: "Paulinho Da Viola",
		key: "D",
		name: "Argumento",
		style: "Samba",
		tempo: 94,
	},
	{
		_id: 17,
		composer: "Muhamad Al Wahab",
		key: "Gm",
		name: "Khatwat Habibi",
		style: "Sirto",
		tempo: 90,
	},
	{
		_id: 18,
		composer: "Paco De Lucia",
		key: "E",
		name: "Barrio La Viña",
		style: "Flamenco",
		tempo: 90,
	},
	{
		_id: 19,
		composer: "Compay Segundo",
		key: "Am",
		name: "Candela",
		style: "Son Cubano",
		tempo: 108,
	},
	{
		_id: 20,
		composer: "Pancho Amat",
		key: "E",
		name: "No Me Quieras Tanto",
		style: "Son Cubano",
		tempo: 110,
	},
	{
		_id: 21,
		composer: "John Coltrane",
		key: "Ab",
		name: "Naima",
		style: "Jazz Balad",
		tempo: 72,
	},
];

@Component({
	selector: "app-root",
	templateUrl: "./app-component.html",
})
export class AppComponent implements OnInit {
	title = "e-songbook";
	ngOnInit() {
		console.log(JSON.stringify(data));
	}
}
